<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdenProduccionDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenProduccionDetalleRepository extends EntityRepository
{
	//
    public function getOrdenProduccionDetalleAsignada($idUsuario = null)
    {
    	if ($idUsuario == null) {
    		$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 1')
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery(); 
    	}else{
    		$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 1 AND opd.responsable = :idUsuario')
	        ->setParameter('idUsuario', $idUsuario)
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();
    	}

        return $query->getResult();
    }

    //
    public function getOrdenProduccionDetalleProduccion($idUsuario = null)
    {
    	if ($idUsuario == null) {
	        $query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 2')
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();
	    }else{
	    	$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 2 AND opd.responsable = :idUsuario')
	        ->setParameter('idUsuario', $idUsuario)
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();	
	    }

        return $query->getResult();
    }

    //
    public function getOrdenProduccionDetalleTerminada($idUsuario = null)
    {
    	if ($idUsuario == null) {
	        $query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 3')
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();
	    }else{
	    	$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 3 AND opd.responsable = :idUsuario')
	        ->setParameter('idUsuario', $idUsuario)
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();	
	    }

        return $query->getResult();
    }

    //
    public function getOrdenProduccionDetalleDespacho($idUsuario = null)
    {
    	if ($idUsuario == null) {
	        $query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 4')
	        ->orderBy('op.id', 'DESC')
	        ->getQuery();
	    }else{
	    	$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 4 AND opd.responsable = :idUsuario')
	        ->setParameter('idUsuario', $idUsuario)
	        ->orderBy('op.id', 'DESC')
	        ->getQuery();	
	       
	    }

	  
        return $query->getResult();
    }

    //
    public function getOrdenProduccionDetalleEntregada($idUsuario = null)
    {
    	if ($idUsuario == null) {
	        $query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 5')
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();
	    }else{
	    	$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 5 AND opd.responsable = :idUsuario')
	        ->setParameter('idUsuario', $idUsuario)
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();	
	    }

        return $query->getResult();
    }

    public function getOrdenProduccionDetalleEntregadaZona($zona,$idUsuario = null)
    {
    	if ($idUsuario == null) {
	        $query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->join('op.zonaEnvio','ze')
	        ->where('opd.ordenProduccionEstado = 3 AND ze.nombre = :nombre_zona')
	        ->setParameter('nombre_zona', $zona)
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();
	    }else{
	    	$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 3 AND opd.responsable = :idUsuario')
	        ->setParameter('idUsuario', $idUsuario)
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();	
	    }

        return $query->getResult();
    }

    //
    public function getOrdenProduccionDetalleProduccionTerminada($idUsuario = null)
    {
    	if ($idUsuario == null) {
	        $query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 2 OR opd.ordenProduccionEstado = 3')
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();
	    }else{
	    	$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('(opd.ordenProduccionEstado = 2 OR opd.ordenProduccionEstado = 3)
	        AND opd.responsable = :idUsuario')
	        ->setParameter('idUsuario', $idUsuario)
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();	
	    }

        return $query->getResult();
    }

    //
    public function getOrdenProduccionDetalleDespachoEntregada($idUsuario = null)
    {
        if ($idUsuario == null) {
	        $query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('opd.ordenProduccionEstado = 4 OR opd.ordenProduccionEstado = 5')
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();
	    }else{
	    	$query = $this->createQueryBuilder('opd')
	        ->join('opd.ordenProduccion', 'op')
	        ->join('op.pedido', 'p')
	        ->where('(opd.ordenProduccionEstado = 4 OR opd.ordenProduccionEstado = 5)
	        AND opd.responsable = :idUsuario')
	        ->setParameter('idUsuario', $idUsuario)
	        ->orderBy('op.prioridad', 'DESC')
	        ->getQuery();	
	    }

        return $query->getResult();
    }
}
